### ISSUE TITLE
Selection UI styling

### ISSUE THREAD

**Issue by AmanGotchu** [tamuhack-org/rattle#2]
The overlays for Event and Attribute selection need to be styled.

**Comment by AmanGotchu** [comment]
No design is made so we'll have to discuss further.

**Comment by gracekfan** [comment]
<img width="288" alt="Screen Shot 2019-07-10 at 10 36 07 PM" src="https://user-images.githubusercontent.com/33182506/61020369-1fac8300-a363-11e9-985d-417e8c837b84.png">

**Comment by OneWebDev** [comment]
This is currently how this page looks. I made a few stylistic / text changes.
![screenshot1](https://user-images.githubusercontent.com/24493949/61412224-ec5f7c00-a8ad-11e9-9556-24b1f1404ceb.PNG)
