### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by AmanGotchu** [tamuhack-org/rattle#29]
Comprehensively add current error handling toasts and redirection to entire application.

Error Handling:
API calls 
User status

Comment if there are other edge cases.

**Comment by OneWebDev** [comment]
Toast Progress
- [ ] Success (Login): Login was correct
- [ ] Error (Login): Login was incorrect
- [ ] Warning (Confirmation Modal): Attribute Mismatch 
- [ ] Error (Confirmation Modal): User not registered
- [ ] Error (Confirmation Modal): Error in API Call
- [ ] Success (Select): User found in search
- [ ] Warning (Select): No User found in search
- [ ] Error (Select): API Call
- [ ] Error (Select): No authorization (not logged in).
