### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by AmanGotchu** [tamuhack-org/rattle#3]
Login screen needs to be created and styled.

![image](https://user-images.githubusercontent.com/14339863/61014781-e7df1480-a33d-11e9-87ae-9a97e8b235c3.png)

**Comment by AmanGotchu** [comment]
Won't be done with Google login.

**Comment by gracekfan** [comment]
<img width="298" alt="Screen Shot 2019-07-10 at 10 36 44 PM" src="https://user-images.githubusercontent.com/33182506/61020390-34891680-a363-11e9-8195-c73ca9845921.png">

**Comment by OneWebDev** [comment]
This is how the current design of this page looks like. Only the styling is done, and some basic error checking. 

![loginpage](https://user-images.githubusercontent.com/24493949/61412455-88898300-a8ae-11e9-9341-f4728192d0dd.PNG)
