### ISSUE TITLE
Style confirmation overlay after scanning

### ISSUE THREAD

**Issue by AmanGotchu** [tamuhack-org/rattle#9]
Design/front-end for the confirmation overlay that pops up after successfully scanning any QR code.

The overlay already exists.

**Comment by gracekfan** [comment]
<img width="350" alt="Screen Shot 2019-07-10 at 10 37 23 PM" src="https://user-images.githubusercontent.com/33182506/61020414-4c609a80-a363-11e9-9486-f1d4244dd506.png">

**Comment by gracekfan** [comment]
Also see: https://github.com/firebase/mlkit-material-android/blob/master/screenshots/live_barcode.gif?raw=true
